version: '3.8'

services:
  app:
    build: 
      context: .
      dockerfile: dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    environment:
      NODE_ENV: development