openapi: 3.0.0
servers:
  # Added by API Auto Mocking Plugin
  - description: SwaggerHub API Auto Mocking
    url: http://localhost:3000
info:
  description: This is a calcultor API
  version: '1'
  title: Calculator
  contact:
    email: omer72@gmail.com
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
tags:
  - name: calcultor
    description: Simple Calculator
paths:
  /generate-token:
    get:
      tags:
        - calcultor
      summary: get the token
      operationId: Token
      description: Get a token
      responses:
        '201':
          description: Successful operation
        '400':
          description: 'Failed to get the token'
  /calculate:
    post:
      tags:
        - calcultor
      summary: calcuate 2 numbers using the action
      operationId: Calculator
      description: Calcuate 2 numbers using the action
      responses:
        '201':
          description: Successful operation
        '400':
          description: 'invalid input, object invalid'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CalculatorValues'
        description: Inventory item to add
      security:
        - bearerAuth: []
components:
  securitySchemes:
    bearerAuth:            # arbitrary name for the security scheme
      type: http
      scheme: bearer
      bearerFormat: JWT    # optional, arbitrary value for documentation purposes
  schemas:
    CalculatorValues:
      type: object
      required:
        - num1
        - num2
        - operation
      properties:
        num1:
          type: number
        num2:
          type: number
        operation:
          type: string
          enum: ["add", "subtract", "multiply", "divide"]
  responses:
    UnauthorizedError:
      description: Access token is missing or invalid